3 вопрос (20 баллов) 
Реализовать методы forward и backward в полносвязном слое. Входные данные обязательно должны быть в 
виде батчей (то есть кол-во измерений в inputs 2). Нельзя использовать готовую реализацию обратного 
распространения из PyTorch.
Шаблон кода, который можно использовать за основу: https://pastebin.com/Ugvjf6PA

In [1]:
import torch
from typing import Optional

class Linear:
    def __init__(self, n_inputs: int, n_neurons: int):
        self.weights = torch.randn(n_inputs, n_neurons) * 0.01
        self.biases = torch.randn(n_neurons) * 0.01
        self.inputs: Optional[torch.Tensor] = None

    def forward(self, inputs: torch.Tensor) -> torch.Tensor:
        assert inputs.ndim == 2
        self.inputs = inputs
        return torch.mm(inputs, self.weights) + self.biases

    def backward(self, dvalue: torch.Tensor) -> None:
        self.dweights = torch.mm(self.inputs.T, dvalue)
        self.dbiases = dvalue.sum(axis=0)

        self.dinput = torch.mm(dvalue, self.weights.T)

linear_layer = Linear(n_inputs=3, n_neurons=2)

inputs = torch.randn(4, 3)

output = linear_layer.forward(inputs)

dvalue = torch.randn(4, 2)

linear_layer.backward(dvalue)

output, linear_layer.dweights, linear_layer.dbiases, linear_layer.dinput

(tensor([[-0.0217,  0.0088],
         [ 0.0057,  0.0133],
         [ 0.0239,  0.0025],
         [-0.0096,  0.0159]]),
 tensor([[-1.4218,  1.6001],
         [-0.5099, -2.2779],
         [-1.4309,  0.7782]]),
 tensor([1.3475, 3.7677]),
 tensor([[-0.0351, -0.0286,  0.0063],
         [-0.0268, -0.0109,  0.0138],
         [ 0.0019, -0.0083, -0.0085],
         [ 0.0043,  0.0253,  0.0172]]))