2 вопрос (20 баллов)
Задать два двумерных тензора ar1 и ar2 размерности (4, 7), состоящих из случайных целых чисел в пределах 
от 0 до 10. Построить двумерный тензор размерности (4, 7), каждый элемент которого представляет собой 
максимум из двух значений, находящихся на аналогичной позиции в тензорах ar1, ar2. 

In [1]:
import torch

ar1 = torch.randint(0, 11, (4, 7))
ar2 = torch.randint(0, 11, (4, 7))

max_tensor = torch.max(ar1, ar2)

ar1, ar2, max_tensor

(tensor([[ 3,  5,  9,  0,  9,  2,  8],
         [ 7,  7,  6,  9, 10, 10,  4],
         [ 3,  6,  1,  0,  7,  7,  5],
         [ 6,  3,  5,  1,  5,  4,  3]]),
 tensor([[ 0,  0,  7,  2,  7,  5,  2],
         [ 8,  0,  4,  4,  9,  2,  7],
         [ 1, 10,  5,  3,  7,  2,  3],
         [ 8,  1,  9,  4,  7,  9,  7]]),
 tensor([[ 3,  5,  9,  2,  9,  5,  8],
         [ 8,  7,  6,  9, 10, 10,  7],
         [ 3, 10,  5,  3,  7,  7,  5],
         [ 8,  3,  9,  4,  7,  9,  7]]))